env:
  matrix:
    - BUILDTYPE=go
    - BUILDTYPE=docker

language: go
go:
- 1.6.2
services:
  - docker

before_install:
  - if [["$BUILDTYPE"=="go"]]; then go get github.com/tools/godep
script:
  -if [["$BUILDTYPE"=="go"]]; then godep restore && godep go build
  -if [["$BUILDTYPE"=="docker"]]; then docker build -t arkenio/provisioningAPI:v1 .
